# -*- coding: utf-8 -*-
"""CA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwM-NLOrrmLv0LMYJuFFi2aNCADNNDXE
"""

def all_but_last(l):
  l = l[:-1]
  return l

#def all_but_last(L):
 # return L[:-1]

print(all_but_last([1, 2, 3]))

print(all_but_last(["apple", "worm", "apple"]))

#def pair_them_up(L1,L2):
 # l= []
 # for i in range(len(L1)):
   # l.append([L1[i], L2[i]])
    #k.append(l[i])
    #l.append(L2[i])
    #k.append(l[i + 1])
 # return l

def pair_them_up(L1,L2):
  l= []
  for i in range(len(L1)):
    l.append([L1[i], L2[i]])

  return l

print(pair_them_up(['The Washington Post', 'Amazon'], ['Bezos', 'Bezos']))

print(pair_them_up(['Tesla', 'Microsoft', 'X', 'Nvidia'], ['Musk', 'Gates', 'Musk', 'Huang']))

def gr_to_net(L):
  p = []
  for gross in L:
    p.append(0.85 * gross - 800)
  return p

print(gr_to_net([10000, 3000, 7600]))

def assemble_list_on_ordinals(L1, L2):
     return [L1 [i - 1] for i in L2]



print(assemble_list_on_ordinals(['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'], [2, 3, 5]))

print(assemble_list_on_ordinals(['apple', 'banana', 'peach', 'blueberry', 'orange'], [1, 4, 2, 2]))

def assemble_list_on_ordinals(L1, L2):
  m = [L1 [i -1] for i in L2]
  return m

print(assemble_list_on_ordinals(['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'], [2, 3, 5]))



o = [99, -7, 54, 36, 75, 7, 99, 75, 7, 99, 75]

def k (l):
  l = []
  y = [l[3:12],l[8:12],l[8:12],l[0:3]]
  for i in y:
    l.append(i)
  return y

print(k([99, -7, 54, 36, 75, 7, 99, 75, 7, 99, 75]))

def k (l):
  p1 = l[2:9]
  p2 = l[::4] *2
  p4 = l[::-1]

  return p1 + p2+p4

print(k([99, -7, 54, 36, 75, 7, 99, 75, 7, 99, 75]))

print(k([1,2,3,4,5,6,7,8,9,10]))

print(k([7, -59, 7, -61, 99, -7, 54, 36, 75, -50, 67, 98]))

def k(l):
  return l[2:9] + l[::4] *2 + l[::-1]

print(k([99, -7, 54, 36, 75, 7, 99, 75, 7, 99, 75]))