# -*- coding: utf-8 -*-
"""Functions_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIgXpOOFI4HaJZALMYAlBHxcmxi6-FOx

**Task 1**
"""

def differ(x,y):
  d = x - y
  return d

differ(4,9)

print(differ(0,0))

"""**Task 2**"""

def hypothenuse(a,b):
  h = (a**2 + b**2)**0.5

  return h
hypothenuse(3,4)

print(round(hypothenuse(3,4),3))

"""**Task 3**"""

#price_to_pay = fruit_price(3,2,9,5)
def fruit_price(n_apples, unit_appl, n_bananas, unit_bana):
  price_to_pay = (n_apples * unit_appl) + (n_bananas * unit_bana)
  return price_to_pay
print(fruit_price(3,2,9,5))

"""**Task 4**"""

def avarage4(a,b,c,d):
  avg = (a+b+c+d) / 4
  return avg

print(avarage4(1,2,3,4))
print(avarage4(0,0,3,0))