# -*- coding: utf-8 -*-
"""Python_task_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxvnOScnD8j7QNayQS0F1i13ICauFQNM

# **Exercises : 1**
* Make Array `c` into pandas
dataframe `dfc`, with the index labels "A" and "B"

* Use once .iloc and once .loc to display dfc with all of its columns except the last one! Can you use slices for this with .loc, too?
* Change the column labels into "one", "two", "three", "four"
* Set the value in the cell defined by the final column and final row to 100 using .loc
* Set the first two cells of the initial row of the dataframe to -100 using .iloc
Set the values in column "three" so that A is "rabbit", B is "fox".
"""

c = [[-1, 3, -1, 15],
     [-1,45,-1,-1]]

pip install pandas

!conda install pandas

import pandas as pd

dfc = pd.DataFrame([[-1, 3, -1, 15], [-1, 45, -1, -1]])

dfc.index=['A','B']

dfc

dfc.columns

dfc.index

dfc.columns = ['one', 'two', 'three', 'four']
dfc

dfc.loc["A":"B", "one":"two"]

dfc.loc[:, "three"]

last_row = dfc.index[-1]
print(last_row)

last_columns = dfc.columns[-1]
print(last_columns)

dfc.loc[last_row, last_columns] = 100
dfc

dfc.iloc[0,1] = -100
dfc

dfc.iloc[0:1]



dfc.loc[["A","B"],["three"]] = ["Rabbit", "Fox"]

dfc["three"]

dfc

"""#**Exercises 2**

* Modify the values in the final column such that the new value is two to the power of the relevant cell value (e.g., if the old value is 3, the new value should be 2**3 = 8)

+ Check the datatypes of the data frame, and try to set all numeric columns to int. If you encounter problems, try to think about how you could at least arrive at some numeric type. (Think about how float is a more general type than int.)

+ In columns where the data types are numeric, set all values to the value in the column with the smallest absolute value.

+ In the initial row, swap the first two values.

+ **Add two to each value** in column "two".
"""

dfc.iloc[[0,1], [3]] = [(15**2), (100**2)]
dfc

type(dfc)