# -*- coding: utf-8 -*-
"""Python_class_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxvnOScnD8j7QNayQS0F1i13ICauFQNM

* Make Array `c` into pandas
dataframe `dfc`, with the index labels "A" and "B"

* Use once .iloc and once .loc to display dfc with all of its columns except the last one! Can you use slices for this with .loc, too?
* Change the column labels into "one", "two", "three", "four"
* Set the value in the cell defined by the final column and final row to 100 using .loc
* Set the first two cells of the initial row of the dataframe to -100 using .iloc
Set the values in column "three" so that A is "rabbit", B is "fox".
"""

c = [[-1, 3, -1, 15],
     [-1,45,-1,-1]]

pip install pandas

!conda install pandas

import pandas as pd

dfc = pd.DataFrame([[-1, 3, -1, 15], [-1, 45, -1, -1]],
                   columns = ["A", "B"])
dfc