# -*- coding: utf-8 -*-
"""Starting_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snNaskobdckkYo0ChiSr8fupBUokIdXB

Install Pandas
"""

pip install pandas

!conda install pandas

import pandas as pd