# -*- coding: utf-8 -*-
"""theory_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNB_6mSfDszuPSi0ob3Oz2ZRcGMiNSYU

**FLOAT**
"""

c = 2.5
print(type(c))

d = 3. #this is a float because of the decimal point.
print(type(d))

print(c+d)

print(d%c)

print(10 ** 100) #arbitrary precision integer)
print(10. ** 100) #float

3.4e2

"""**Boolean**"""

a = True; b = False
print(type(a & b))

"""

*   True & True = `True`
*   True AND False = `False`


*   False AND true = `False`
*   False & false = `False`










"""

#logical and
print (a and b)
print (a & a)

"""
*   True | True = `True`
*   True OR False = `True`


*   False OR true = `True`
*   False OR false = `False`


Logic example : If you want to get a discount, you must be a student **or** a senior citizen"""

print (not a)
print (not b)

"""In fact, Booleans are a subtype of integers, True = 1, False = 0"""

1

"""**Operation on sets**
<img src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Op%C3%A9rations_ensembles_sets_operations.png" width=350px>

Worthwhile getting to know, can be really useful. Analogy to logical operators!

* `&` = intersection ("AND", $\cap$)
* `|` = union ("OR", $\cup$)
* `-` = difference ("AND NOT", , $\setminus$)
"""